first_name = input('Please type your first name: ')
last_name = input('Please type your last name: ') 
email_address = input('Please type your email address: ') 
phone_number = input('Please type your phone number: ') 
job_title = input('Please type your job title: ') 
id_number = input('Please type your ID Number: ') 

print('')
print('-------------------------')
print(f'{last_name.upper()}, {first_name.lower().capitalize()}')
print(f'{job_title.lower().capitalize()}')
print(f'ID Number: {id_number}')
print('')
print(f'{email_address.lower()}')
print(f'{phone_number}')
print('-------------------------')
print('')