print('Please enter the following')
print('')
food = input('food: ')
name = input('name: ')
adjective = input('adjective: ')
noun = input('noun: ')
verb = input('verb: ')
verb_two = input('verb: ')
verb_three = input('verb: ')

print('')
print('Your story is: ')
print('')
print(f'It was {food} day at school, and {name.capitalize()} was super {adjective} for lunch. But when she went outside to eat, a {noun} stole her {food}! {name.capitalize()} chased the {noun} all over school. She {verb}, {verb_two}, and {verb_three} through the playground. Then she tripped on her {noun} and the {noun} escaped! Luckily, {name.capitalize()} friends were willing to share their {food} with her.')
