print('Please enter the following')
print('')
adjective = input('adjective: ')
animal = input('animal: ')
verb = input('verb: ')
exclamantion = input('exclamation: ')
verb_two = input('verb: ')
verb_three = input('verb: ')
print('')
print('Your story is: ')
print('')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb} down the hallway. "{exclamantion}!" I yelled. But allI could think to do was to {verb_two} over and over. Miraculously,that caused it to stop, but not before it tried to {verb_three} right in front of my family. ')
